- src/test/java/net/mekomsolutions/eip/routes/senaite/TestApplicationPropertiesPresentITest.java
> INFRA-263: Minor fix on failing test

- README.md
- pom.xml
- routes/senaite/inbound-lims-route.xml
- routes/senaite/outbound-lims-route.xml
- routes/senaite/test_order-from-order-creator-route.xml
- src/test/java/net/mekomsolutions/eip/routes/senaite/TestConfiguration.java
- src/test/resources/application.properties
Ticket: https://issues.openmrs.org/browse/EIP-15
> EIP-15: Updating watcher version, documentation and dependent package.

- routes/senaite/authenticate-toOpenmrs-route.xml
Ticket: https://issues.openmrs.org/browse/EIP-57
> EIP-57: Adding support for OAuth2 with OpenMRS.

- routes/senaite/create-serviceRequestResults-to-openmrs-route.xml
- routes/senaite/create-serviceRequestTask-to-openmrs-route.xml
- routes/senaite/fetch-serviceRequestTasks-from-openmrs-route.xml
- routes/senaite/listenTo-openmrs-route.xml
- routes/senaite/poll-senaite-route.xml
- routes/senaite/process-contactNames-route.xml
- routes/senaite/process-patientNames-route.xml
- routes/senaite/update-serviceRequest-task-to-openmrs-route.xml
- src/test/java/net/mekomsolutions/eip/routes/senaite/CreateServiceRequestResultsToOpenmrsRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/CreateServiceRequestTaskToOpenmrsRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/FetchServiceRequestTasksFromOpenmrsRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/ListenToOpenmrsITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/PollSenaiteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/ProcessContactNamesRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/ProcessPatientNamesRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/UpdateServiceRequestTaskToOpenmrsRouteITest.java
- src/test/resources/application.properties
Ticket: https://issues.openmrs.org/browse/EIP-81
> EIP-81: Changing FHIR URI from '*ws/fhir2/R4*' to '*ms/fhir2Servlet*'.

- routes/senaite/create-serviceRequestResults-to-openmrs-route.xml
- src/test/java/net/mekomsolutions/eip/routes/senaite/CreateServiceRequestResultsToOpenmrsRouteITest.java
- src/test/resources/application.properties
TIcket: https://issues.openmrs.org/browse/EIP-86
> EIP-86: SENAITE routes to handle coded test results and based on an expected obs grouping structure

- routes/senaite/authenticate-to-openmrs-route.xml
- routes/senaite/authenticate-to-senaite-route.xml
- routes/senaite/cancel-order-to-senaite-route.xml
- routes/senaite/create-analysisRequest-to-senaite-route.xml
- routes/senaite/create-client-to-senaite-route.xml
- routes/senaite/create-contact-to-senaite-route.xml
- routes/senaite/create-serviceRequestTask-to-openmrs-route.xml
- routes/senaite/process-serviceRequest-taskState-route.xml
- routes/senaite/retrieve-contactNames-route.xml
- routes/senaite/retrieve-patientId-route.xml
- routes/senaite/retrieve-patientNames-route.xml
- routes/senaite/retrieve-patientUuid-route.xml
- routes/senaite/update-client-to-senaite-route.xml
See [slack conversation](https://openmrs.slack.com/archives/C0178G3A1T7/p1667502435851389?thread_ts=1667309377.675099&cid=C0178G3A1T7).
> OZ-86: Allowing errors to bubble up to parent routes.

- routes/senaite/create-serviceRequestTask-to-openmrs-route.xml
- src/test/java/net/mekomsolutions/eip/routes/senaite/CreateServiceRequestTaskToOpenmrsRouteITest.java
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-111
> OZ-111: Create FHIR Task for ServiceRequest only if none exists

- routes/senaite/create-analysisrequest-to-senaite-route.xml
- routes/senaite/create-servicerequest-results-to-openmrs-route.xml
- routes/senaite/create-servicerequest-task-to-openmrs-route.xml
- routes/senaite/fetch-servicerequest-tasks-from-openmrs-route.xml
- routes/senaite/listen-to-openmrs-route.xml
- routes/senaite/listenTo-openmrs-route.xml
- routes/senaite/poll-senaite-route.xml
- routes/senaite/process-servicerequest-task-state-route.xml
- routes/senaite/retrieve-orderer-names-from-openmrs-route.xml
- routes/senaite/retrieve-patient-id-from-openmrs-route.xml
- routes/senaite/retrieve-patient-names-from-openmrs-route.xml
- routes/senaite/retrieve-patient-uuid-from-openmrs-route.xml
- routes/senaite/update-serviceRequest-task-to-openmrs-route.xml
- routes/senaite/write-bahmniOrder-as-openmrsOrder-route.xml
- src/test/java/net/mekomsolutions/eip/routes/senaite/CreateAnalysisRequestToSenaiteRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/CreateServiceRequestResultsToOpenmrsRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/CreateServiceRequestTaskToOpenmrsRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/FetchServiceRequestTasksFromOpenmrsRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/ListenToOpenmrsITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/PollSenaiteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/ProcessServiceRequestTaskStateRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/RetrieveContactNamesRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/RetrievePatientIdRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/RetrievePatientNamesRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/RetrievePatientUuidRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/UpdateServiceRequestTaskToOpenmrsRouteITest.java
- src/test/java/net/mekomsolutions/eip/routes/senaite/WriteBahmniOrderAsOpenmrsOrderRouteITest.java
- src/test/resources/application.properties
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-111
> OZ-111: Route names and file names using kebab-case.

- routes/senaite/openmrs-to-senaite-event-listener-route.xml
- src/test/java/net/mekomsolutions/eip/routes/senaite/ListenToOpenmrsITest.java
- src/test/resources/application.properties
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-111
> OZ-111: Refactoring 'listen-to-openmrs'to 'openmrs-to-senaite-event-listener'

- .gitignore
- pom.xml
- routes/senaite/create-analysisrequest-to-senaite-route.xml
- routes/senaite/create-servicerequest-results-to-openmrs-route.xml
- src/test/java/com/ozonehis/eip/routes/senaite/AuthenticateToOpenmrsRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/AuthenticateToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CancelOrderToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CreateAnalysisRequestToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CreateClientToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CreateContactToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CreateServiceRequestResultsToOpenmrsRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CreateServiceRequestTaskToOpenmrsRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/FetchServiceRequestTasksFromOpenmrsRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/ListenToOpenmrsITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/PollSenaiteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/ProcessServiceRequestTaskStateRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/RetrieveContactNamesRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/RetrievePatientIdRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/RetrievePatientNamesRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/RetrievePatientUuidRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/TestApplicationPropertiesPresentITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/TestConfiguration.java
- src/test/java/com/ozonehis/eip/routes/senaite/UpdateClientToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/UpdateServiceRequestTaskToOpenmrsRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/WriteBahmniOrderAsOpenmrsOrderRouteITest.java
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-351
> OZ-351: `net.mekomsolutions` → `com.ozonehis`.

- .github/workflows/ci.yml
- .ocd3.yml
- pom.xml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-438
Build, test, and publish using GitHub Actions.
> OZ-438: Build, test and publish using Github Actions

- .github/workflows/check-deps.yml
- .github/workflows/ci.yml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-438
> OZ-438: Use check-deps shared GitHub Actions workflows.

- src/main/resources/camel/create-servicerequest-results-to-openmrs-route.xml
- src/test/java/com/ozonehis/eip/routes/senaite/CancelOrderToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CreateClientToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/CreateContactToSenaiteRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/RetrieveContactNamesRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/RetrievePatientNamesRouteITest.java
- src/test/java/com/ozonehis/eip/routes/senaite/WriteBahmniOrderAsOpenmrsOrderRouteITest.java
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-348
This PR fixes Polling from SENAITE camel route.
> OZ-348: strategyRef → aggregationStrategy split option.

- src/main/resources/eip-openmrs-senaite.properties
Issue: https://mekomsolutions.atlassian.net/browse/OZ-475
Provides sensible OAuth2 defaults
> OZ-475: Provide appropriate OAuth2 configuration defaults.

- pom.xml
Ticket→ [OZ-498](https://mekomsolutions.atlassian.net/browse/OZ-498)
This PR prepares release for SENAITE routes version 2.0.0.
[OZ-498]: https://mekomsolutions.atlassian.net/browse/OZ-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prepare for next development iteration 

- senaite-openmrs/src/main/java/com/ozonehis/eip/openmrs/senaite/handlers/openmrs/ServiceRequestHandler.java
JIRA: https://mekomsolutions.atlassian.net/browse/OZ-624?focusedCommentId=45679
> OZ-624: Fix error `Resource of type ServiceRequest with ID is gone/deleted`

- README.md
This PR fixes README.md build failures in the spotless check job.
> OZ-340: Fix README.md spotless check

- integration-tests/pom.xml
- pom.xml
- senaite-openmrs/pom.xml
- test-infra-senaite/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-784
> Prepare for next development iteration

- senaite-openmrs/src/main/resources/config/application.properties
JIRA: https://mekomsolutions.atlassian.net/browse/OZ-558
> OZ-558: application.properties enriched for MkDocs auto-parsing.

- senaite-openmrs/src/main/resources/config/application.properties
JIRA: https://mekomsolutions.atlassian.net/browse/OZ-558
> OZ-558: Remove `location` field from Ozone Docs
